application: kck-answerspace
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: latest

handlers:
# Serving static files
- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: admin

#Main handler
- url: /.*
  script: answerspace.application
  login: required

